-- INSERT INTO people (id, first_name, last_name) VALUES (1,"Groucho","Marx");
-- INSERT INTO people (id, first_name, last_name) VALUES(2,"Zeppo", "Marx");
-- INSERT INTO people (id, first_name, last_name) VALUES(3,"Harpo", "Marx");
-- INSERT INTO people (id, first_name, last_name) VALUES(4,"Gummo", "Marx");
