User.destroy_all

u1 = User.create :username => "admin", :email => "simon@kingforadaydesign.com", :image => "http://www.fillmurray.com/200/200", :password => "chicken", :password_confirmation => "chicken", :admin => true
u2 = User.create :username => "admin", :email => "steve@ga.co", :image => "http://www.fillmurray.com/200/200", :password => "chicken", :password_confirmation => "chicken"


Art.destroy_all

block = Art.create :name => "Question Block",
  :cells => [
    [[false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false]],
    [[false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false]],
    [[true, "000000", false], [false, false, false], [false, false, false], [true, "f7d73b", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [true, "f7d73b", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [true, "f7d73b", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [true, "f7d73b", false], [false, false, false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "f7d73b", false], [false, false, false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "f7d73b", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [false, false, false], [true, "f7d73b", false], [true, "f7d73b", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "f7d73b", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false]],
    [[true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false]],
    [[false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false]],
    [[false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false]]
  ], :user_id => 1

  mushroom = Art.create :name => "Mushroom",
    :cells => [
      [[false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false]],
      [[false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false]],
      [[false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false]],
      [[false, false, false], [false, false, false], [true, "000000", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "000000", false], [false, false, false], [false, false, false]],
      [[false, false, false], [true, "000000", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "000000", false], [false, false, false]],
      [[false, false, false], [true, "000000", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "000000", false], [false, false, false]],
      [[true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false]],
      [[true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false]],
      [[true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false]],
      [[true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false]],
      [[true, "000000", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "000000", false]],
      [[true, "000000", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "000000", false]],
      [[true, "000000", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "a22f21", false], [true, "a22f21", false], [true, "a22f21", false], [true, "000000", false]],
      [[false, false, false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false]],
      [[false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false]],
      [[false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false]],
      [[false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false]],
      [[false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false]],
      [[false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false]],
      [[false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [true, "000000", false], [false, false, false], [false, false, false], [false, false, false], [false, false, false], [false, false, false]]
    ], :user_id => 1
