answers = Game.create :answer => "It is certain"
answers = Game.create :answer => "It is decidedly so"
answers = Game.create :answer => "Without a doubt"
answers = Game.create :answer => "Without a doubt"
answers = Game.create :answer => "Yes, definitely"
answers = Game.create :answer => "You may rely on it"
answers = Game.create :answer => "As I see it, yes"
answers = Game.create :answer => "Most likely"
answers = Game.create :answer => "Outlook good"
answers = Game.create :answer => "Yes"
answers = Game.create :answer => "Signs point to yes"
answers = Game.create :answer => "Reply hazy try again"
answers = Game.create :answer => "Ask again later"
answers = Game.create :answer => "Better not tell you now"
answers = Game.create :answer => "Cannot predict now"
answers = Game.create :answer => "Concentrate and ask again"
answers = Game.create :answer => "Don't count on it"
answers = Game.create :answer => "My reply is no"
answers = Game.create :answer => "My sources say no"
answers = Game.create :answer => "Outlook not so good"
answers = Game.create :answer => "Very doubtful"
