Eightball.destroy_all

Eightball.create :answer => "It is certain"
Eightball.create :answer => "It is decidedly so"
Eightball.create :answer => "Without a doubt"
Eightball.create :answer => "Yes, definitely"
Eightball.create :answer => "You may rely on it"
Eightball.create :answer => "As I see it, yes"
Eightball.create :answer => "Most likely"
Eightball.create :answer => "Outlook good"
Eightball.create :answer => "Yes"
Eightball.create :answer => "Signs point to yes"
Eightball.create :answer => "Reply hazy try again"
Eightball.create :answer => "Ask again later"
Eightball.create :answer => "Better not tell you now"
Eightball.create :answer => "Cannot predict now"
Eightball.create :answer => "Concentrate and ask again"
Eightball.create :answer => "Don't count on it"
Eightball.create :answer => "My reply is no"
Eightball.create :answer => "My sources say no"
Eightball.create :answer => "Outlook not so good"
Eightball.create :answer => "Very doubtful"
